# Generated by Django 5.0.3 on 2025-03-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('result_code', models.CharField(blank=True, max_length=100, null=True)),
                ('result_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
