# Generated by Django 5.0.2 on 2025-03-15 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('card', 'Credit/Debit Card')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='mpesapayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='reference',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='result_code',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='result_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['phone_number'], name='main_mpesap_phone_n_f897ed_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['transaction_id'], name='main_mpesap_transac_0704c4_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['status'], name='main_mpesap_status_5f1f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference'], name='main_paymen_referen_c61398_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='main_paymen_transac_808749_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='main_paymen_status_c7dd8f_idx'),
        ),
    ]
