# Generated by Django 5.0.2 on 2025-03-16 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_paymenttransaction_alter_mpesapayment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('tracking_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('package_type', models.CharField(choices=[('small', 'Small Package'), ('medium', 'Medium Package'), ('large', 'Large Package'), ('extra_large', 'Extra Large Package'), ('document', 'Document'), ('fragile', 'Fragile Item')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dimensions', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_fragile', models.BooleanField(default=False)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('pickup_location', models.TextField()),
                ('pickup_date', models.DateTimeField()),
                ('delivery_location', models.TextField()),
                ('estimated_delivery', models.DateTimeField()),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('status_history', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference_number'], name='main_order_referen_20c634_idx'), models.Index(fields=['tracking_number'], name='main_order_trackin_6e1a4c_idx'), models.Index(fields=['current_status'], name='main_order_current_4c0d9f_idx'), models.Index(fields=['created_at'], name='main_order_created_a818a5_idx')],
            },
        ),
    ]
